baseUrl = 'http://plan.ru.website.yandexcloud.net'
title = "Behold, my links!"

enableEmoji = true

[params.author]
  name = "Pavel Reshetnikov"
  headline = "Programming enthusiast, DnD game master, fan of metalcore, j-pop and jazz"
  image = "ReshetnikovPavel.jpg"
  links = [
    { link = { href = "https://github.com/ReshetnikovPavel", text = "Github", icon = "github" } },
    { link = { href = "https://t.me/reshetnikovpavel", text = "Telegram", icon = "telegram" } },
    { link = { href = "https://social.linux.pizza/@pavelresh", text = "Mastodon", icon = "mastodon" } },
  ]
